#include-once

Global Const $ACCEPTED_OPPONENT = "bot.session.battle.accepted_opponent"
Global Const $REJECTED_OPPONENT = "bot.session.battle.rejected_opponent"
Global Const $ACCEPTED_LOG = "bot.session.battle.accepted_log"
Global Const $SPAWN_INITIAL_DIRECTION = "bot.session.spawn.direction"
Global Const $SPAWN_MIN = "bot.session.spawn.min"
Global Const $SPAWN_MAX = "bot.session.spawn.max"
Global Const $RT_SPAWN_LAST_DIRECTION = "bot.session.runtime.spawn.last_direction"
Global Const $RT_ON_BATTLE_VISIBLE = "bot.session.runtime.battle.on_visible"
Global Const $RT_ON_BATTLE_START = "bot.session.runtime.battle.on_start"
Global Const $RT_ON_BATTLE_STOP = "bot.session.runtime.battle.on_stop"
Global Const $RT_RAW_TEXT = "bot.session.runtime.battle.raw_text"
Global Const $RT_RAW_LOG = "bot.session.runtime.battle.raw_log"
Global Const $RT_RECOGNISED_OPPONENT = "bot.session.runtime.battle.recogised_opponent"
Global Const $RT_IS_ACTIONABLE = "bot.session.runtime.battle.actionable"
Global Const $RT_ACTION = "bot.session.runtime.battle.action"
Global Const $RT_STATE = "bot.session.runtime.state"